# Creating our Sequences/Data Windows

## Preapring the dataset

In [5]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("../raw_data/data/merged_data_prescaling.csv")

In [4]:
df.head(2)

Unnamed: 0        time     bdi          cgdp        csteel        CIP
0           1  1995-01-23  1983.0  5.890383e+11  7.349355e+06  14.721669
1           2  1995-01-30  1959.0  5.923030e+11  7.317968e+06  15.351956

In [6]:
df.set_index("time", inplace=True)

In [8]:
df.drop(columns="Unnamed: 0", inplace=True)

In [53]:
df.head(20)

bdi          cgdp        csteel        CIP
time                                                     
1995-01-23  1983.0  5.890383e+11  7.349355e+06  14.721669
1995-01-30  1959.0  5.923030e+11  7.317968e+06  15.351956
1995-02-06  1980.0  5.955677e+11  7.418464e+06  15.812899
1995-02-13  1992.0  5.988324e+11  7.571714e+06  16.125851
1995-02-20  2027.0  6.020971e+11  7.724964e+06  16.312167
1995-02-27  2066.0  6.053618e+11  7.878214e+06  16.393198
1995-03-06  2176.0  6.086264e+11  7.978774e+06  16.387777
1995-03-13  2266.0  6.118911e+11  8.058258e+06  16.289972
1995-03-20  2289.0  6.151558e+11  8.137742e+06  16.079792
1995-03-27  2209.0  6.184205e+11  8.217226e+06  15.737088
1995-04-03  2205.0  6.216852e+11  8.269333e+06  15.242233
1995-04-10  2247.0  6.249499e+11  8.253000e+06  14.621283
1995-04-17  2299.0  6.282145e+11  8.236667e+06  13.980773
1995-04-24  2347.0  6.314792e+11  8.220333e+06  13.435436
1995-05-01  2343.0  6.347439e+11  8.204000e+06  13.100000
1995-05-08  2299.0  6.380086e+11  8.113903e+06  13.052435
1995-05-15  2208.0  6.412733e+11  8.023806e+06  13.223668
1995-05-22  2129.0  6.445380e+11  7.933710e+06  13.507864
1995-05-29  2055.0  6.478027e+11  7.843613e+06  13.799190
1995-06-05  1995.0  6.510673e+11  7.783933e+06  13.995420

## TimeseriesGenerator

In [25]:
X = df
y = df["bdi"]

In [46]:
X.shape

(1391, 4)

In [47]:
y.shape

(1391,)

In [28]:
#Question: since past values of the BDI are also features that can be used to predict future values of the bdi,
#should I preserve the bdi values? 

In [48]:
data_gen = TimeseriesGenerator(data=X, targets=y, length=8, sampling_rate=1, stride=1)

In [52]:
for X, y in data_gen:
    print(X.shape, y.shape)
    print(X[0], y[0])
    break 

(128, 8, 4) (128,)
[[1.98300000e+03 5.89038329e+11 7.34935484e+06 1.47216694e+01]
 [1.95900000e+03 5.92303014e+11 7.31796774e+06 1.53519559e+01]
 [1.98000000e+03 5.95567699e+11 7.41846429e+06 1.58128989e+01]
 [1.99200000e+03 5.98832384e+11 7.57171429e+06 1.61258515e+01]
 [2.02700000e+03 6.02097068e+11 7.72496429e+06 1.63121668e+01]
 [2.06600000e+03 6.05361753e+11 7.87821429e+06 1.63931980e+01]
 [2.17600000e+03 6.08626438e+11 7.97877419e+06 1.63877772e+01]
 [2.26600000e+03 6.11891123e+11 8.05825806e+06 1.62899717e+01]] 2289.0
